### ISSUE TITLE
vs2019 编译出来的NCNN 测试，在cmd界面输出都是乱码，请问怎么解决？

### ISSUE THREAD

**Issue by xpston008** [benjaminwan/OcrLiteNcnn#6]
C:\Users\admin\Desktop\Project_OcrLiteNcnn-1.7.0\ncnnocr\Release>ncnnocr.exe --models models --det det --cls cls --rec rec --keys keys.txt --image 1.jpg --GPU 0

modelsPath=models
model dbnet path=models/det
model angle path=models/cls
model crnn path=models/rec
keys path=models/keys.txt
imgDir=, imgName=1.jpg
Model dbnet file not found: models/det.param

C:\Users\admin\Desktop\Project_OcrLiteNcnn-1.7.0\ncnnocr\Release>ncnnocr.exe --models models  --keys keys.txt --image 1.jpg --GPU 0
modelsPath=models
keys path=models/keys.txt
imgDir=, imgName=1.jpg
resultTxtPath(1.jpg-result.txt)
=====Input Params=====
numThread(4),padding(50),maxSideLen(1024),boxScoreThresh(0.600000),boxThresh(0.300000),unClipRatio(2.000000),doAngle(1),mostAngle(1),GPU(0)
=====Init Models=====
--- Init DbNet ---
--- Init AngleNet ---
--- Init CrnnNet ---
=====Start detect=====
ScaleParam(sw:740,sh:740,dw:736,dh:736,0.994595,0.994595)
---------- step: dbNet getTextBoxes ----------
dbNetTime(496.365100ms)
TextBox[0](+padding)[score(0.735103),[x: 314, y: 58], [x: 668, y: 433], [x: 622, y: 476], [x: 268, y: 102]]
TextBox[1](+padding)[score(0.770903),[x: 435, y: 53], [x: 691, y: 305], [x: 635, y: 362], [x: 379, y: 110]]
TextBox[2](+padding)[score(0.791785),[x: 263, y: 122], [x: 564, y: 460], [x: 500, y: 515], [x: 201, y: 178]]
TextBox[3](+padding)[score(0.794584),[x: 182, y: 176], [x: 483, y: 530], [x: 415, y: 589], [x: 114, y: 234]]
TextBox[4](+padding)[score(0.699193),[x: 109, y: 230], [x: 320, y: 501], [x: 255, y: 552], [x: 44, y: 281]]
---------- step: drawTextBoxes ----------
---------- step: angleNet getAngles ----------
angle[0][index(1), score(0.999997), time(7.265200ms)]
angle[1][index(1), score(0.999786), time(2.394500ms)]
angle[2][index(1), score(0.999846), time(2.373200ms)]
angle[3][index(1), score(0.791865), time(2.258000ms)]
angle[4][index(1), score(1.000000), time(2.451200ms)]
---------- step: crnnNet getTextLine ----------
textLine[0](棣欐腐娣卞湷鎶借锛屽彲閭瘎)
textScores[0]{0.996313 ,0.999845 ,0.999914 ,0.999713 ,0.999677 ,0.998594 ,0.999956 ,0.999995 ,0.995888 ,0.998597}
crnnTime[0](27.478900ms)
textLine[1](涓撲笟鏌ユ€у埆)
textScores[1]{0.999805 ,0.576728 ,0.993639 ,0.999157 ,0.999847}
crnnTime[1](16.519200ms)
textLine[2](涓撲笟閴村畾B瓒呭崟)
textScores[2]{0.999981 ,0.999988 ,0.999614 ,0.999997 ,0.999606 ,0.999977 ,0.999962}
crnnTime[2](19.265100ms)
textLine[3](b瓒呬华鍣ㄦ煡鎬у埆)
textScores[3]{0.985631 ,0.999934 ,0.993689 ,0.982854 ,0.958149 ,0.996716 ,0.999792}
crnnTime[3](22.646900ms)
textLine[4](鍔犲井淇ee)
textScores[4]{0.987057 ,0.984709 ,0.969712 ,0.880784 ,0.790944 ,0.988959}
crnnTime[4](14.586800ms)
=====End detect=====
FullDetectTime(628.647800ms)
棣欐腐娣卞湷鎶借锛屽彲閭瘎
涓撲笟鏌ユ€у埆
涓撲笟閴村畾B瓒呭崟
b瓒呬华鍣ㄦ煡鎬у埆
鍔犲井淇ee

**Comment by benjaminwan** [comment]
OCR输出的字符编码是UTF8，cmd的默认编码是GBK。
参考https://blog.csdn.net/liaomingwu/article/details/122986769

在执行运行指令前，增加chcp指令修改cmd编码
chcp 65001
ncnnocr.exe --models models --keys keys.txt --image 1.jpg --GPU 0

**Comment by benjaminwan** [comment]
为何不使用提供的run-test.bat呢
https://github.com/benjaminwan/OcrLiteNcnn/blob/master/run-test.bat

**Comment by xpston008** [comment]
谢谢！已解决。
但在exsi Win7+ vs2019 ，昨天尝试了chcp 65001 编码，是乱码。
今天物理机win10+vs2015，尝试了一下，正常了。

**Comment by benjaminwan** [comment]
Windows7执行错误|中文乱码
1.cmd窗口左上角-属性
2.字体选项卡-选择除了“点阵字体”以外的TrueType字体,例如:Lucida Console、宋体
3.重新执行bat
